name: New metadata property
description: Form to suggest a new metadata property to be added to metadata schemas.
title: "[New prop.]: "
labels: ["enhancement", "new property"]
assignees:
  - M-casado
body:
  - type: markdown
    attributes:
      value: |
        This form serves as a template for **new fields or properties**. It can be used to add, for example, a new field to the ``assay_technology_descriptor`` of the common definitions' schema (e.g. ``assay_provider``) or to add a whole new schema. We highly recommend for proposed terms to be ontologised when applicable. 
        Thank you for contributing to the metadata standards of the European Genome-phenome Archive (EGA)!

  - type: dropdown
    id: metadata-object
    attributes:
      label: Metadata object(s)
      description: What metadata object(s) does the new term correspond to? Take a look at the metadata diagram [**here**](https://github.com/EbiEga/ega-metadata-schema/tree/main/docs/metadata_model).
      multiple: true
      options:
        - Analysis
        - Experiment
        - Assay
        - Sample
        - Individual
        - DAC
        - Policy
        - Dataset
        - Study
        - Submission
        - New
        - Other/unsure
    validations:
      required: true

  - type: input
    id: property-title
    attributes:
      label: Property title
      description: What is the proposed property title? You can find the set of current schemas [**here**](https://github.com/EbiEga/ega-metadata-schema/tree/main/schemas) and its rendered markdown [**here**](https://github.com/EbiEga/ega-metadata-schema/tree/main/docs/json_browser).
      placeholder: e.g. Technology provider
    validations:
      required: true
  
  - type: dropdown
    id: property-type
    attributes:
      label: Type(s) of property
      description: Please select the type(s) of the proposed property. Check JSON schema [documentation](http://json-schema.org/understanding-json-schema/reference/type.html) on type-specific keywords. Select ``--unsure--`` if you are not sure which type it could be.
      multiple: true
      options:
        - string
        - number
        - integer
        - object
        - array
        - boolean
        - "null"
        - --unsure--
    validations:
      required: false    

  - type: input
    id: property-curie
    attributes:
      label: Property CURIE
      description: What is the CURIE (Compact URI) of the proposed property (if applicable)? You can find the CURIE of your property by searching by name at the [Ontology Lookup Service (OLS)](https://www.ebi.ac.uk/ols/index). A CURIE consists in an ontology preffix followed by a colon (e.g. EFO:) and an accession of the term within the ontology (e.g. 0001729).
      placeholder: e.g. NCIT:C142729
    validations:
      required: false

  - type: textarea
    id: property-description
    attributes:
      label: Property description
      description: What is the description of the proposed property? It can be copied from the ontology record if applicable. 
      placeholder: e.g. An individual or organization that sells software applications or computer hardware. 
    validations:
      required: true
    
  - type: input
    id: parent-property
    attributes:
      label: Parent property
      description: What is the parent property of the proposed property? If the proposed property is expected to be at "root" level of the schema, please specify "root". 
      placeholder: e.g. assay_technology
    validations:
      required: false

  - type: textarea
    id: required-optional
    attributes:
      label: Required property?
      description: Should the proposed property be required or optional? In case the property was optionally required (i.e. depending on the context, values or other properties), please provide more details of which scenarios it should be required in. 
      placeholder: e.g. Optional 
    validations:
      required: true

  - type: textarea
    id: controlled-vocabulary
    attributes:
      label: Controlled Vocabulary (CV)
      description: Please specify if the property shall have a controlled vocabulary (i.e. restricted value list). If so, please give details on which values it should take or if we should take the ontology values as the CV.
      placeholder: Any provider name should be accepted, hence no CV shall be needed.
    validations:
      required: false
  
  - type: textarea
    id: value-examples
    attributes:
      label: Value examples
      description: Please provide examples (one per line) of the value the new property would take. Can be ommitted if the Controlled Vocabulary (CV) was specified.
      placeholder: |
          Affymetrix
          Agilent
          Thermofisher
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: "Provide here any extra context, for example including: why the new property is needed, your motivation, why the current schemas do not meet your needs..."
      placeholder: This new property is similar to the assay_instrument_platform, but we believe in some cases it could be beneficial to have them as separate properties...
    validations:
      required: false