@startjson

{
    "data": {
        "assayTypeSpecifications": {
            "sequencingAssaySpecifications": {
                "referenceAlignmentDetails": [
                    {
                        "ncbiAssembly": {
                            "termId": "assembly:GCF_000001405.26"
                        },
                        "ncbiAssemblyUnit": {
                            "termId": "refseq:NC_000001.11"
                        }
                    },
                    {
                        "ncbiAssembly": {
                            "termId": "assembly:GCF_000001405.26"
                        },
                        "ncbiAssemblyUnit": {
                            "termId": "refseq:NC_000002.12"
                        }
                    }
                ]
            }
        }
    }
}
@endjson