@startjson

{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "https://raw.githubusercontent.com/EbiEga/ega-metadata-schema/main/schemas/EGA.submission.json",
    "type": "object",
    "title": "EGA submission metadata schema",
    "meta:version": "0.0.0",
    "$async": true,
    "description": "Metadata schema used by the European Genome-phenome Archive (EGA) to validate \\nits Submission (also known as submission project) metadata object. This object \\nis intended to be an object that others can reference, grouping them by \\nsubmission details. An EGA user can submit metadata comprising thousands of \\nobjects, or just a few that suffice the bare minimum of a comprehensive \\nsubmission: at least one dataset, with its proper links to other objects. A \\nsubmission JSON document hold little details, mainly the basic descriptive \\nfields and collaborators array, but its main use is for other objects to \\nreference it. Further details can be found in the EGA-metadata-schema GitHub \\nrepository (https://github.com/EbiEga/ega-metadata-schema/tree/main/schemas).",
    "required": [
        "objectId"
    ],
    "additionalProperties": false,
    "properties": {
        "objectId": "{ ... }",
        "schemaDescriptor": "{ ... }",
        "objectTitle": "{ ... }",
        "objectDescription": "{ ... }",
        "resources": "{ ... }",
        "additionalCollaborators": "{ ... }",
        "submissionRelationships": "{ ... }",
        "submissionAttributes": "{ ... }"
    }
}
@endjson