#Configuration for defining which fields in which worksheets to be parsed in the
#AMP-T2D submission pack V2 spreadsheet.
#
#At the top level, "worksheets" defines a list of worksheets (titles) to be parsed.
#Then for each worksheet, you define which fields to be parsed from this worksheet.
#These fields are either "required" or "optional". "required" fields must be found
#in the worksheet so that this worksheet is valid. Otherwise this worksheet is not
#valid. The field names must match those values in the header row in the worksheet.
#
#This is a YAML file

# Worksheet specific requirements
sample:
  required:
      - Sample_alias
      - Center_name
      - Title
      - NCBI_taxid
      - Scientific_name
      - Common_name
      - Description
      - Tag
      - Value
      - Units

run:
    required:
        - Run_alias
        - Center_name
        - Run_date
        - Experiment_reference
        - Filename
        - Filetype
        - Checksum_method
        - Encrypted_checksum
        - Unencrypted_checksum

study:
    required:
        - Study_alias
        - Center_name
        - Study_title
        - Existing_study_type
        - Study_abstract
        - Tag
        - Value
        - Units

analysis:
    required:
        - Analysis_alias
        - Center_name
        - Analysis_date
        - Title
        - Description
        - Study_alias
        - Study_CenterName
        - Assembly_name
        - Assembly_accession
        - Sequence_accession
        - Sequence_label
        - Experiment_type
        - Sample_alias
        - Sample_CenterName
        - Label
        - Filename
        - Filetype
        - Checksum_method
        - Encrypted_checksum
        - Unencrypted_checksum
        - Tag
        - Value
        - Units
