#Configuration for defining which fields in which worksheets to be parsed in the
#AMP-T2D submission pack V2 spreadsheet.
#
#At the top level, "worksheets" defines a list of worksheets (titles) to be parsed.
#Then for each worksheet, you define which fields to be parsed from this worksheet.
#These fields are either "required" or "optional". "required" fields must be found
#in the worksheet so that this worksheet is valid. Otherwise this worksheet is not
#valid. The field names must match those values in the header row in the worksheet.
#
#This is a YAML file

# Worksheet specific requirements
sample:
  required:
      - Sample_alias*
      - Center_name*
      - Title*
      - NCBI_taxid*
      - Scientific_name*
      - Common_name*
      - Tag
      - Value
      - Units

run:
    required:
      - Run_alias*
      - Center_name*
      - ExperimentReference_Name*

study:
    required:
      - Study_alias*
      - Center_name*
      - Study_title*
      - Existing_study_type*

analysis:
    required:
      - Analysis_alias*
      - Center_name*
      - Analysis_type*
      
experiment:
    required:
      - Experiment_alias*
      - Center_name*
      - Experiment_layout*
      - Study_refname*
      - Design_description*
      - Sample_accession*
      - Library_strategy*
      - Library_source*
      - Library_selection*
      - Platform*

dataset:
    required:
      - Dataset_alias*
      - Center_name*
      - Dataset_title*


submission:
    required:
      - Submission_alias*
      - Center_name*

dac:
    required:
      - DAC_alias*
      - Center_name*
      - CONTACT.name
      - CONTACT.email
      - CONTACT.organisation

policy:
    required:
      - Policy_alias*
      - Center_name*
      - Policy_source*
      - DAC_accession*      