---
# This workflow checks that the semantic versioning (e.g. 1.1.0) of the JSON
#   schemas is correct.
# The logic of this workflow is:
#   - Details: EE-2699
#   - Why: it helps avoiding human errors of versions in the schemas not being 
#       changed when or how they should.
#   - Would block the PR if failed? Yes, as long as the PR is for a release.
#   - How: by executing the script version_modification_check.py, and then,
#       based on its output, deploying Biovalidator with the old and new schemas
#       and old and new JSON examples.
#
# For more information, check:
#   https://github.com/EbiEga/ega-metadata-schema/tree/main/docs/releases

name: |
  [REQUIRED] Check schema semantic versioning

on:
  pull_request:
    branches: [main]
    # We only want for it to be triggered when JSON Schemas change in the PR
    paths:
      - 'schemas/**.json'

jobs:
  check-modifications:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # This bit is needed to checkout in the branch that triggered the action
          #   (e.g. v2.0.1)
          ref: ${{ github.head_ref }}

      - uses: actions/setup-python@v4
        with:
          # We'll use the latest version of python from major 3 release
          # This bit is needed for running the following python script
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          requirements_f="./.github/scripts/requirements.txt"
          if [ -f "$requirements_f" ]; then pip install -r "$requirements_f"; fi

      - name: Run version modification check
        id: run-version-modification-check
        run: |
          # We get the list of modified JSON files
          json_files=$(git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} -- schemas/ | grep -E '\.json$')
          script_path="./.github/scripts/version_modification_check.py"

          python3 "$script_path" --strict_mode --set_output_gh_action "version_needs_to_be_checked" --files "$json_files"
        
        # The output of this previous script will determine if changes are not "major" (i.e. minor or patch), and therefore retrocompatibility
        #   has to be tested through JSON Schema validation (combination of old and new schemas with old and new examples).
        #   Thus, only if the variable "version_needs_to_be_checked" from the script is True, the following steps will occur.

      #!
      # - name: Handle version modification check result
      #   if: ${{ steps.run-version-modification-check.outputs.version_needs_to_be_checked == 'True' }}
      #   run: |          
      #     if [[ "${{ steps.run-version-modification-check.outputs.version_needs_to_be_checked }}" == "True" ]]; then
      #       echo "#! Is version_needs_to_be_checked truly the output?"
      #     fi

      - name: Clone Biovalidator
        if: ${{ steps.run-version-modification-check.outputs.version_needs_to_be_checked == 'True' }}
          # See https://github.com/elixir-europe/biovalidator#installation
        run: git clone https://github.com/elixir-europe/biovalidator.git

      - name: Install Biovalidator
        if: ${{ steps.run-version-modification-check.outputs.version_needs_to_be_checked == 'True' }}
        run: |
          cd biovalidator
          npm install
          # We shouldn't need to audit the issues, but for now it is what it is
          npm audit fix

      - name: Start Biovalidator server (old schemas)
        if: ${{ steps.run-version-modification-check.outputs.version_needs_to_be_checked == 'True' }}
          # We want to specify the OLD JSON schemas, so we DO NOT specify the schemas
          #   at deployment level, and instead let Biovalidator fetch them from "main"
        run: |         
          node biovalidator/src/biovalidator &
          
          # We stop for a few seconds to give the server some time
          sleep 3

      - name: Validate JSON examples (old schemas, new examples)
        if: ${{ steps.run-version-modification-check.outputs.version_needs_to_be_checked == 'True' }}
          # Validate NEW JSON documents against the OLD (from "main") schemas
        run: |
          json_ex_dir="./examples/json_validation_tests"
          # The following URL points to the locally deployed server of
          #   Biovalidator
          url="http://localhost:3020/validate"

          python3 ./.github/scripts/request_validation.py "$json_ex_dir" "$url"


      - name: Start Biovalidator server (New schemas)
        if: ${{ steps.run-version-modification-check.outputs.version_needs_to_be_checked == 'True' }}
          # We want to specify the NEW JSON schemas, so we DO specify the schemas
          #   at deployment level
        run: |
          schemas_dir="./schemas"          
          node biovalidator/src/biovalidator -r "$schemas_dir/*.json" &

          # We stop for a few seconds to give the server some time
          sleep 3

      - name: Validate JSON examples (New schemas, old examples)
        if: ${{ steps.run-version-modification-check.outputs.version_needs_to_be_checked == 'True' }}
          # Validate OLD JSON documents against the NEW (from branch) schemas
        run: |
          # We fetch all old JSON examples from "main"
          old_json_ex_dir="./examples/old_json_validation_tests"
          json_ex_dir="./examples/json_validation_tests"
          python3 fetch_github_documents.py --input_directory "$json_ex_dir" --destination_directory "$old_json_ex_dir"

          # The following URL points to the locally deployed server of
          #   Biovalidator
          url="http://localhost:3020/validate"

          python3 ./.github/scripts/request_validation.py "$old_json_ex_dir" "$url"
