---
# This workflow validates the current JSON documents against EGA's JSON schemas
# using EGA's API endpoint (http://biovalidator.ega.ebi.ac.uk/validate) of
# the tool Biovalidator (https://github.com/elixir-europe/biovalidator) and the
# up-to-date EGA JSON schemas (https://github.com/EbiEga/ega-metadata-schema/tree/main/schemas).
# The logic of this workflow is:
#   - Why: It allows us to know if the changes introduced in the branch are
#          compliant with the default (main branch) schemas.
#   - Would block the PR if failed? No, it's just informative.
#   - How: perform POST requests to EGA's API using the branch's 
#          JSON example files.
# For more information, check:
#   https://github.com/EbiEga/ega-metadata-schema/tree/main/docs/gh_workflows
name: JSON docs validation - EGA API (json_validation_against_EGA_API.yml)

on:
  # Executes on any commit to a PR to the "main" branch
  pull_request:
    branches: [main]

jobs:
  validate-json-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history
          fetch-depth: 0

      - name: Validate JSON examples
        # Validate all JSON documents against their corresponding schemas
        run: |
          json_ex_dir="./examples/json_validation_tests"

          # Loop through the examples and validate each against the API
          for json_filepath in "$json_ex_dir"/*.json; do 
                  json_filename=$( basename "$json_filepath" )
                  curl --data @"$json_filename" \
                    -H "Content-Type: application/json" \
                    -X POST "biovalidator.ega.ebi.ac.uk/validate"
          done